### ISSUE TITLE
FastBogoSort doesn't run in O(n log n)!

### ISSUE THREAD

**Issue by derek1906** [sordina/IneffectiveSorts#1]
By reading the source code in details, I have confirmed that this line does not run in O(1):

```
random.shuffle(l)
```

Thus the program is not O(n log n)!

The program's speed is very crucial to our algorithm.

volvo pls fix

**Comment by sordina** [comment]
Wow this is embarrassing... Can't believe it slipped through.

**Comment by sordina** [comment]
f2df966  - Updated the documentation to reflect the real complexity of the algorithm!

**Comment by derek1906** [comment]
Nice fix!

**Comment by sordina** [comment]
How did you find the repo by the way?

**Comment by derek1906** [comment]
I was bored and since someone made a successful implementation of StackSort, I was wondering if someone else made an implementation of the FastBogoSort, and indeed someone did.
